import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { PGlite } from "@electric-sql/pglite";
import { drizzle } from "drizzle-orm/pglite";
import { eq, and, sql } from "drizzle-orm";
import express from "express";
import { transformSync } from "esbuild";
import { transferenciasCotas } from "../shared/schema";
import { canCorrectQuotaTransfer, quotaCorrectionSchema } from "../shared/quota-correction";
import { calculateMap } from "../shared/member-portfolio";

test("corrige pela API com histórico atômico, revalida permissões e preserva caixa", async () => {
  const pg = new PGlite();
  await pg.exec(`CREATE TABLE transferencias_cotas (id varchar PRIMARY KEY, bia_id varchar NOT NULL, membro_origem_id varchar NOT NULL, membro_destino_id varchar NOT NULL, valor_total numeric, percentual_transferencia numeric(5,2), status text NOT NULL, solicitado_por varchar, observacoes text, anexos text[], motivo_rejeicao text, criado_em timestamp DEFAULT now(), atualizado_em timestamp DEFAULT now());`);
  await pg.exec(readFileSync(new URL("../migrations/20260915_quota_corrections.sql", import.meta.url), "utf8"));
  const db = drizzle(pg);
  await db.insert(transferenciasCotas).values({ id: "test", bia_id: "bia", membro_origem_id: "origem", membro_destino_id: "destino", valor_total: "349.89", percentual_transferencia: "100", status: "aceita", anexos: ["anexo-ç.pdf"], observacoes: "Original" });
  const storageSource = readFileSync(new URL("./storage.ts", import.meta.url), "utf8");
  const startMethod = storageSource.indexOf("  async correctTransferenciaCotas(");
  const method = storageSource.slice(startMethod, storageSource.indexOf("  async updateTransferenciaCotas(", startMethod));
  const Store = new Function("db", "transferenciasCotas", "eq", "and", "sqlExpr", transformSync(`class Store { ${method} }; return Store;`, { loader: "ts" }).code)(db, transferenciasCotas, eq, and, sql);
  const storage = new Store();
  storage.getTransferenciaCotas = async (id: string) => (await db.select().from(transferenciasCotas).where(eq(transferenciasCotas.id, id)))[0];
  const app = express(); app.use(express.json());
  app.use((req: any, _res, next) => { req.session = req.headers["x-role"] ? { directusUserId: "test-user", role: req.headers["x-role"], membroId: req.headers["x-member"] } : {}; next(); });
  const source = readFileSync(new URL("./routes.ts", import.meta.url), "utf8");
  const start = source.indexOf('  app.patch("/api/transferencia-cotas/:id/correcao"');
  const route = source.slice(start, source.indexOf('  app.get("/api/transferencia-cotas"', start));
  new Function("app", "storage", "requireBiaModuleAccess", "directusFetchOne", "canCorrectQuotaTransfer", "quotaCorrectionSchema", transformSync(route, { loader: "ts" }).code)(app, storage,
    async (req: any, res: any) => { if (req.headers["x-denied"]) { res.status(403).json({error:"Sem acesso à BIA"}); return false; } return true; },
    async () => ({ diretor_alianca: { id: "diretor" }, aliado_built: "aliado" }), canCorrectQuotaTransfer, quotaCorrectionSchema);
  app.get("/fixture", async (_req, res) => res.json(await storage.getTransferenciaCotas("test")));
  const server = app.listen(0, "127.0.0.1");
  await new Promise<void>(resolve => server.once("listening", resolve));
  const base = `http://127.0.0.1:${(server.address() as any).port}`;
  const read = async () => (await fetch(`${base}/fixture`)).json();
  const patch = (body: any, headers: Record<string,string> = { "x-role": "admin" }) => fetch(`${base}/api/transferencia-cotas/test/correcao`, { method:"PATCH", headers:{"Content-Type":"application/json", ...headers}, body:JSON.stringify(body) });
  try {
    const original = await read();
    const input = { valor_total: 174.94, percentual_transferencia: 50, motivo: 'Correção João d’Ávila & Cia + "Sul"\nvalor digitado errado', atualizado_em: original.atualizado_em };
    assert.equal((await patch(input, {})).status, 401);
    assert.equal((await patch(input, {"x-role":"user", "x-member":"origem"})).status, 403);
    assert.equal((await patch(input, {"x-role":"admin", "x-member":"origem"})).status, 403);
    assert.equal((await patch(input, {"x-role":"admin", "x-denied":"yes"})).status, 403);
    for (const bad of [{valor_total:0}, {valor_total:-1}, {valor_total:"174,94"}, {valor_total:1.001}, {percentual_transferencia:101}, {motivo:" "}]) assert.equal((await patch({...input,...bad})).status, 400);
    assert.deepEqual(await read(), original);
    assert.equal((await patch(input, {"x-role":"user", "x-member":"diretor"})).status, 200);
    const corrected = await read();
    assert.equal(corrected.valor_total, "174.94");
    assert.equal(corrected.status, "aceita");
    assert.equal(corrected.criado_em, original.criado_em);
    assert.deepEqual(corrected.anexos, original.anexos);
    assert.equal(corrected.correcoes[0].antes.valor_total, "349.89");
    assert.equal(corrected.correcoes[0].autor_id, "test-user");
    assert.equal(corrected.correcoes[0].motivo, input.motivo);
    assert.equal((await patch(input)).status, 409);
    const contributions = [{memberId:"origem", value:1000, status:"pago"}];
    const map = calculateMap(contributions, [{status:corrected.status, fromMemberId:corrected.membro_origem_id, toMemberId:corrected.membro_destino_id, value:Number(corrected.valor_total)}]);
    assert.equal(map.find(row=>row.memberId==="destino")?.value, 174.94);
    assert.equal(map.reduce((sum,row)=>sum+row.value,0),1000);
    assert.deepEqual(contributions,[{memberId:"origem",value:1000,status:"pago"}]);
    const retry = {...input, atualizado_em:corrected.atualizado_em, valor_total:200};
    const concurrent = await Promise.all([patch(retry), patch({...retry,valor_total:250})]);
    assert.deepEqual(concurrent.map(r=>r.status).sort(),[200,409]);
    const beforeReversal = await read();
    assert.equal(beforeReversal.correcoes.length,2);
    const reversal = { acao: "reverter", confirmar: true, motivo: 'Reversão — operação duplicada & conferida + "OK"\nç', atualizado_em: beforeReversal.atualizado_em };
    assert.equal((await patch({...reversal, confirmar:false})).status,400);
    assert.equal((await patch({...reversal, motivo:" "})).status,400);
    assert.equal((await patch(reversal, {"x-role":"user", "x-member":"origem"})).status,403);
    assert.deepEqual(await read(),beforeReversal);
    assert.equal((await patch(reversal)).status,200);
    const reversed = await read();
    assert.equal(reversed.status,"revertida");
    assert.equal(reversed.valor_total,beforeReversal.valor_total);
    assert.deepEqual(reversed.anexos,original.anexos);
    assert.equal(reversed.correcoes.length,3);
    assert.equal(reversed.correcoes[2].acao,"reverter");
    assert.equal(reversed.correcoes[2].antes.status,"aceita");
    assert.equal(reversed.correcoes[2].depois.status,"revertida");
    assert.equal(reversed.correcoes[2].motivo,reversal.motivo);
    assert.equal((await patch({...reversal, atualizado_em:reversed.atualizado_em})).status,409);
    assert.equal((await patch({...input, atualizado_em:reversed.atualizado_em})).status,409);
    const restoredMap = calculateMap(contributions,[{status:reversed.status, fromMemberId:"origem",toMemberId:"destino",value:Number(reversed.valor_total)}]);
    assert.equal(restoredMap.find(row=>row.memberId==="origem")?.value,1000);
    assert.equal(restoredMap.find(row=>row.memberId==="origem")?.percent,100);
    assert.equal(restoredMap.find(row=>row.memberId==="destino"),undefined);
  } finally { await new Promise<void>(resolve=>server.close(()=>resolve())); await pg.close(); }
});
