import { Fragment, useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { BiaLegalPersonField } from "./bia-legal-person-field";
import { BiaNumberInput } from "./bia-role-composition";
import { BiaInformationFields, EMPTY_BIA_INFO } from "./bia-information-fields";
import { ASSET_METRICS, ASSET_STATES, LEGAL_TYPES, LEGAL_STATES, assetTotals, type BiaSetup } from "@shared/bia-setup";

const css="min-h-10 w-full rounded-md border bg-background px-3 text-sm";
type Props={value:BiaSetup;onChange:(value:BiaSetup)=>void;participants?:Array<{memberId?:string|null;nome:string}>;bank?:boolean;bankEdit?:boolean;disabled?:boolean};
export function BiaLegalFields({value,onChange,participants=[],bank=true,bankEdit=true,disabled=false}:Props) {
  const j=value.juridico;
  const patch=(data:Partial<typeof j>)=>onChange({...value,juridico:{...j,...data}});
  return <section className="space-y-5 rounded-lg border p-5"><h2 className="text-xl font-semibold">Estrutura Jurídica da BIA</h2>
    <p className="text-sm text-muted-foreground">O quadro societário não é o MAP. Sócios formais não recebem acesso ou participação econômica automaticamente.</p>
    <label className="block">Modelo de formalização<select className={css} value={j.modalidade} onChange={e=>patch({modalidade:e.target.value as typeof j.modalidade})}><option value="">Selecione</option><option value="societaria">Societária</option><option value="contratual">Contratual</option></select></label>
    {j.modalidade==="societaria" && <div className="grid gap-4 sm:grid-cols-2"><label>Tipo societário<select className={css} value={j.tipo} onChange={e=>patch({tipo:e.target.value as typeof j.tipo})}><option value="">Selecione</option>{LEGAL_TYPES.map(t=><option key={t}>{t}</option>)}</select></label><label>Situação<select className={css} value={j.situacao} onChange={e=>patch({situacao:e.target.value as typeof j.situacao})}><option value="">Selecione</option>{LEGAL_STATES.map(t=><option key={t}>{t}</option>)}</select></label><label>Objeto social<Input value={j.objeto} onChange={e=>patch({objeto:e.target.value})}/></label><BiaLegalPersonField label="Administrador" value={j.administrador} disabled={disabled} onChange={administrador=>patch({administrador})}/><label>Capital social<BiaNumberInput label="Capital social" value={j.capitalSocial ?? NaN} onChange={v=>patch({capitalSocial:Number.isFinite(v)?v:null})}/></label></div>}
    {j.modalidade==="contratual" && <div className="grid gap-4 sm:grid-cols-2"><label>Tipo/nome do instrumento<Input value={j.instrumento} onChange={e=>patch({instrumento:e.target.value})}/></label><label>Situação do instrumento<Input value={j.situacaoInstrumento} onChange={e=>patch({situacaoInstrumento:e.target.value})}/></label></div>}
    <div className="grid gap-4 sm:grid-cols-2"><BiaLegalPersonField label="Responsável jurídico *" value={j.responsavel} disabled={disabled} onChange={responsavel=>patch({responsavel})}/><label>OAB do responsável jurídico *<Input value={j.oabResponsavel || ""} maxLength={100} placeholder="Ex.: SP 123456" onChange={e=>patch({oabResponsavel:e.target.value})}/></label></div>
    <BiaInformationFields section="legal" requireAsset={false} infoForm={{...EMPTY_BIA_INFO,...j.info}} setInfoForm={update=>patch({info:typeof update==="function"?update({...EMPTY_BIA_INFO,...j.info}):update})}/>
    {j.modalidade==="societaria" && <div className="space-y-3"><h3 className="font-semibold">Quadro societário formal</h3>{j.socios.map((s,i)=><div key={s.id} className="grid gap-3 rounded border p-3 sm:grid-cols-2"><label>Participante da BEI ou terceiro<select className={css} value={s.memberId} onChange={e=>{const p=participants.find(p=>p.memberId===e.target.value);patch({socios:j.socios.map((r,n)=>n===i?{...r,memberId:e.target.value,nome:p?.nome || r.nome}:r)});}}><option value="">Terceiro / preenchimento manual</option>{participants.filter(p=>p.memberId).map(p=><option key={p.memberId} value={p.memberId || ""}>{p.nome}</option>)}</select></label>{([['nome','Nome / razão social'],['documento','CPF/CNPJ']] as const).map(([k,label])=><label key={k}>{label}<Input value={s[k]} onChange={e=>patch({socios:j.socios.map((r,n)=>n===i?{...r,[k]:e.target.value}:r)})}/></label>)}<label>Quantidade de quotas societárias<BiaNumberInput label={`Quotas societárias de ${s.nome}`} value={s.cotas ?? NaN} decimals={5} onChange={v=>patch({socios:j.socios.map((r,n)=>n===i?{...r,cotas:Number.isFinite(v)?v:null}:r)})}/></label><Button variant="ghost" onClick={()=>{if(window.confirm("Remover este sócio formal? O MAP não será alterado."))patch({socios:j.socios.filter(r=>r.id!==s.id)});}}>Remover sócio formal</Button></div>)}<Button variant="outline" onClick={()=>patch({socios:[...j.socios,{id:crypto.randomUUID(),memberId:"",nome:"",documento:"",cotas:null}]})}>Adicionar sócio formal</Button></div>}
    {bank && <fieldset disabled={!bankEdit} className="space-y-2"><p className="text-sm text-muted-foreground">Conta da empresa ou do responsável jurídico, não da BIA.</p><BiaInformationFields section="bank" requireAsset={false} infoForm={{...EMPTY_BIA_INFO,...j.info}} setInfoForm={update=>patch({info:typeof update==="function"?update({...EMPTY_BIA_INFO,...j.info}):update})}/></fieldset>}
    <p className="text-sm text-muted-foreground">Documentos jurídicos podem ser incluídos nos Anexos dos Dados da BIA. Não geram solicitação de assinatura automaticamente.</p>
  </section>;
}
export function BiaAssetFields({value,onChange,moeda,indicators=true,indicatorsEdit=true}:{value:BiaSetup;onChange:(v:BiaSetup)=>void;moeda:string;indicators?:boolean;indicatorsEdit?:boolean}) {
  const latest=useRef({value,onChange});latest.current={value,onChange};
  const [portfolioOpen,setPortfolioOpen]=useState(false),[search,setSearch]=useState('');
  const portfolio=useQuery<BiaSetup['ativos']>({queryKey:['/api/carteira/imoveis?para_bia=1'],enabled:portfolioOpen,queryFn:async()=>{
    const data=await (await apiRequest('GET','/api/carteira/imoveis?para_bia=1')).json();
    if(!Array.isArray(data) || data.some(a=>!a?.carteiraImovelId || !a.info || typeof a.nome!=='string'))throw new Error('Resposta da Carteira incompatível. Atualize o servidor e tente novamente.');
    return data;
  }});
  const normalize=(text:string)=>text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('pt-BR');
  const options=(portfolio.data || []).filter(a=>normalize([a.nome,a.info.ativo_cidade,a.info.ativo_endereco].join(' ')).includes(normalize(search.trim()))).sort((a,b)=>a.nome.localeCompare(b.nome,'pt-BR'));
  const patch=(id:string,data:Partial<BiaSetup['ativos'][number]>)=>onChange({...value,ativos:value.ativos.map(a=>a.id===id?{...a,...data}:a)});
  return <section className="space-y-5"><h2 className="text-xl font-semibold">Ativos Vinculados</h2><p className="text-sm text-muted-foreground">Cadastro informativo em {moeda}. Não transfere propriedade, gera lançamentos ou altera a fase da BIA.</p>
    <Button type="button" variant="outline" aria-expanded={portfolioOpen} onClick={()=>setPortfolioOpen(!portfolioOpen)}>Adicionar da Carteira</Button>
    {portfolioOpen && <div className="space-y-3 rounded-lg border bg-muted/20 p-4">
      <h3 className="font-semibold">Selecionar ativos da Carteira</h3>
      <p className="text-sm text-muted-foreground">Escolha um ou mais ativos que você administra. Nome, endereço e descrição serão copiados para esta BIA e ficarão visíveis a quem pode consultar sua estrutura. Valores, documentos e titularidade não são importados; alterações aqui não modificam a Carteira.</p>
      <Input aria-label="Buscar ativo na Carteira" placeholder="Buscar por nome, cidade ou endereço" value={search} onChange={e=>setSearch(e.target.value)}/>
      {portfolio.isPending?<p role="status">Carregando Carteira…</p>:portfolio.isError?<div role="alert">Não foi possível carregar a Carteira. <Button type="button" variant="outline" onClick={()=>portfolio.refetch()}>Tentar novamente</Button></div>:<>
        <div className="max-h-72 space-y-2 overflow-y-auto">{options.map(asset=>{
          const added=value.ativos.some(a=>a.carteiraImovelId===asset.carteiraImovelId);
          return <div key={asset.carteiraImovelId} className="flex flex-wrap items-center justify-between gap-3 rounded border bg-background p-3"><div className="min-w-0 flex-1"><p className="break-words font-medium">{asset.nome}</p><p className="break-words text-sm text-muted-foreground">{[asset.info.ativo_cidade,asset.info.ativo_estado].filter(Boolean).join(' / ') || 'Localização não informada'}</p></div><Button type="button" variant="outline" disabled={added || value.ativos.length>=100} aria-label={`${added?'Já adicionado':'Adicionar'}: ${asset.nome}`} onClick={()=>{
            const current=latest.current;
            if(current.value.ativos.length>=100 || current.value.ativos.some(a=>a.carteiraImovelId===asset.carteiraImovelId))return;
            current.onChange({...current.value,ativosIndefinidos:false,ativos:[...current.value.ativos,{...asset,id:crypto.randomUUID()}]});
          }}>{added?'Já adicionado':'Adicionar'}</Button></div>;
        })}</div>
        {!options.length && <p role="status">{portfolio.data?.length?'Nenhum ativo corresponde à busca.':'Nenhum ativo disponível. São exibidos apenas ativos não arquivados de sua propriedade ou com administração compartilhada.'}</p>}
      </>}
      <p className="text-sm text-muted-foreground">A seleção só é gravada ao salvar o rascunho ou a alteração da estrutura.</p>
      <Button type="button" variant="ghost" onClick={()=>setPortfolioOpen(false)}>Concluir seleção</Button>
    </div>}
    <label className="flex gap-2"><input type="checkbox" disabled={!!value.ativos.length} checked={value.ativosIndefinidos} onChange={e=>onChange({...value,ativosIndefinidos:e.target.checked})}/>Ativo ainda não definido</label>
    {value.ativos.map((a,i)=><article key={a.id} className="space-y-4 rounded-lg border p-5"><h3 className="font-semibold">Ativo {i+1}</h3><div className="grid gap-4 sm:grid-cols-2"><label>Nome do ativo<Input value={a.nome} onChange={e=>patch(a.id,{nome:e.target.value})}/></label><label>Situação<select className={css} value={a.situacao} onChange={e=>patch(a.id,{situacao:e.target.value as typeof a.situacao})}><option value="">Não informada</option>{ASSET_STATES.map(s=><option key={s}>{s}</option>)}</select></label><label>Titular formal<Input value={a.titular} onChange={e=>patch(a.id,{titular:e.target.value})}/></label><label>Data de vínculo<Input type="date" value={a.dataVinculo} onChange={e=>patch(a.id,{dataVinculo:e.target.value})}/></label><label>Valor de referência ({moeda})<BiaNumberInput label={`Valor de referência do ativo ${i+1}`} value={a.valorReferencia ?? NaN} onChange={v=>patch(a.id,{valorReferencia:Number.isFinite(v)?v:null})}/></label></div>
      {a.carteiraImovelId && <p className="text-sm text-muted-foreground">Adicionado da Carteira · cópia informativa. <a className="underline" href={`/carteira/${encodeURIComponent(a.carteiraImovelId)}`} target="_blank" rel="noreferrer">Ver cadastro original</a></p>}
      <BiaInformationFields section="asset" requireAsset={false} infoForm={{...EMPTY_BIA_INFO,...a.info}} setInfoForm={update=>{const current=latest.current;current.onChange({...current.value,ativos:current.value.ativos.map(asset=>asset.id!==a.id?asset:{...asset,info:typeof update==="function"?update({...EMPTY_BIA_INFO,...asset.info}):update})});}}/>
      {indicators && <details><summary>Indicadores do ativo</summary><fieldset disabled={!indicatorsEdit} className="mt-3 grid gap-3 sm:grid-cols-2">{ASSET_METRICS.map(([k,label,d])=><label key={k}>{label}<BiaNumberInput label={`${label} — ativo ${i+1}`} decimals={d} value={a.indicadores[k] ?? NaN} onChange={v=>patch(a.id,{indicadores:{...a.indicadores,[k]:Number.isFinite(v)?v:null}})}/></label>)}</fieldset></details>}
      <Button variant="ghost" className="text-destructive" onClick={()=>{if(window.confirm("Remover este cadastro informativo de ativo?"))onChange({...value,ativos:value.ativos.filter(r=>r.id!==a.id)});}}>Remover ativo</Button></article>)}
    <Button type="button" variant="outline" disabled={value.ativos.length>=100} onClick={()=>onChange({...value,ativosIndefinidos:false,ativos:[...value.ativos,{id:crypto.randomUUID(),nome:"",situacao:"A definir",titular:"",dataVinculo:"",valorReferencia:null,info:{...EMPTY_BIA_INFO},indicadores:Object.fromEntries(ASSET_METRICS.map(([k])=>[k,null]))}]})}>Cadastrar ativo manualmente</Button>
    <AssetTotals value={value} moeda={moeda}/>
  </section>;
}
function AssetTotals({value,moeda}:{value:BiaSetup;moeda:string}) {
  const totals=assetTotals(value);
  return <div className="rounded border p-3 text-sm"><h3 className="font-semibold">Consolidado dos ativos informados</h3>{Object.entries(totals).map(([k,v])=><p key={k}>{({valorReferencia:"Valor de referência",valor_geral_venda_vgv:"VGV",valor_realizado_venda:"Vendas realizadas"} as Record<string,string>)[k]}: {v===null?"Não informado":v.toLocaleString('pt-BR',{style:'currency',currency:moeda})}</p>)}<p className="text-muted-foreground">Percentuais não são somados. Ativos sem valores não entram nos totais.</p>{ASSET_METRICS.some(([k])=>value.indicadoresLegados[k]!=null) && <details><summary>Indicadores legados não distribuídos (fora do consolidado)</summary>{ASSET_METRICS.map(([k,label])=>value.indicadoresLegados[k]!=null && <p key={k}>{label}: {value.indicadoresLegados[k]?.toLocaleString('pt-BR')}</p>)}</details>}</div>;
}
export function BiaSetupSummary({value,moeda,anexos=[]}:{value:BiaSetup;moeda:string;anexos?:string[]}) {
  const j=value.juridico;
  const assetLabels:Record<string,string>={qualificacao:'Qualificação',descricao_adicional:'Descrição adicional',area_m2:'Área (m²)',endereco:'Endereço',numero:'Número',complemento:'Complemento',cep:'CEP',bairro:'Bairro',cidade:'Cidade',estado:'Estado',pais:'País',numero_matricula:'Matrícula',livro:'Livro',folha:'Folha',cartorio:'Cartório',comarca:'Comarca'};
  const rows=[["Formalização",j.modalidade==="societaria"?"Societária":j.modalidade==="contratual"?"Contratual":""],["Tipo",j.modalidade==='societaria'?j.tipo:j.instrumento],["Situação",j.modalidade==='societaria'?j.situacao:j.situacaoInstrumento],["Responsável jurídico",j.responsavel],["OAB do responsável jurídico",j.oabResponsavel],...(j.documentoResponsavel?[["CPF/CNPJ do responsável (legado)",j.documentoResponsavel]]:[]),["Razão social",j.info.razao_social],["CNPJ/CPF",j.info.cnpj],["Nome fantasia",j.info.nome_fantasia],["Inscrição estadual",j.info.inscricao_estadual],["Objeto social",j.objeto],["Administrador",j.administrador],["Capital social",j.capitalSocial?.toLocaleString('pt-BR',{style:'currency',currency:moeda})],["Banco",j.info.banco],["Agência / conta",[j.info.agencia,j.info.conta].filter(Boolean).join(' / ')],["Tipo / titular da conta",[j.info.tipo_conta,j.info.titular_conta].filter(Boolean).join(' / ')],["Chave PIX",j.info.chave_pix]];
  return <><section data-pdf-section="juridico" className="space-y-3 rounded border p-5"><h2 className="text-xl font-semibold">Estrutura Jurídica</h2><dl className="grid gap-2 text-sm sm:grid-cols-2">{rows.map(([k,v])=><Fragment key={k}><dt>{k}</dt><dd className="break-words">{v || 'Não informado'}</dd></Fragment>)}</dl><h3>Quadro societário — separado do MAP</h3>{j.socios.map(s=><p key={s.id}>{s.nome} · {s.documento || 'Documento não informado'} · {s.cotas ?? '—'} quotas societárias</p>)}</section>
    <section data-pdf-section="ativos" className="space-y-4 rounded border p-5"><h2 className="text-xl font-semibold">Ativos Vinculados</h2>{!value.ativos.length && <p>Ativo ainda não definido</p>}{value.ativos.map(a=><div data-pdf-asset key={a.id}><h3 className="font-semibold">{a.nome || 'Ativo sem nome'}</h3><p>{a.situacao || 'Situação não informada'} · {a.titular || 'Titular não informado'} · {a.dataVinculo || 'Data não informada'}</p><p>Referência: {a.valorReferencia?.toLocaleString('pt-BR',{style:'currency',currency:moeda}) || 'Não informada'}</p>{Object.entries(a.info).filter(([k,v])=>k.startsWith('ativo_') && v).map(([k,v])=><p key={k}>{assetLabels[k.replace('ativo_','')] || k}: {v}</p>)}{ASSET_METRICS.map(([k,label,d])=>a.indicadores[k]!=null && <p key={k}>{label}: {a.indicadores[k]?.toLocaleString('pt-BR',d===2?{style:'currency',currency:moeda}:{maximumFractionDigits:5})}</p>)}</div>)}<AssetTotals value={value} moeda={moeda}/></section>
    <section data-pdf-section="documentos" className="rounded border p-5"><h2 className="text-xl font-semibold">Documentos informativos</h2>{anexos.length?anexos.map((id,i)=><p key={id}><a href={`/api/assets/${id}`} target="_blank" rel="noreferrer">Anexo {i+1}</a></p>):<p>Nenhum anexo informado.</p>}<p>Os anexos não substituem os aceites obrigatórios do fluxo vigente.</p></section></>;
}
