import { useQuery } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { BiaNumberInput } from "./bia-role-composition";
import { BIA_PARTICIPANT_ROLE_FIELDS, BIA_PARTICIPANT_ROLE_LABELS } from "@shared/bia-access";
import { formatBiaNumber, formatBiaPercent } from "@shared/bia-numbers";
import type { InitialEconomicStructure, InitialMapParticipantInput } from "@shared/member-portfolio";

export const emptyEconomicStructure: InitialEconomicStructure = {modalidade:"recursos_proprios", totalCotas:NaN, instrumentos:[], integralizacao:{forma:"parcelado",quantidade:NaN,primeiroVencimento:"",meses:1,correcao:"Sem reajuste"}};
const roles = ["Contribuição individual", ...Object.keys(BIA_PARTICIPANT_ROLE_FIELDS).map(r=>BIA_PARTICIPANT_ROLE_LABELS[r as keyof typeof BIA_PARTICIPANT_ROLE_FIELDS])];
const selectCss = "min-h-10 w-full min-w-0 rounded-md border bg-background px-2 text-sm";
const natureLabel = (name:string) => name.replace(/^CPP\s*(?:de\s+)?/i, "");
const modalities = {recursos_proprios:"Recursos próprios",consorcio:"Consórcio",financiamento:"Financiamento",mista:"Mista",outra:"Outra"};
export function EconomicMapPreview({map,moeda="BRL"}:{map:{valorOrigem:number;divisorMultiplicador:number;estrutura?:InitialEconomicStructure;participantes:Array<InitialMapParticipantInput & {cppCapitalPercentual?:number;mapPercentual?:number}>};moeda?:string}) {
  const money=(n:number)=>n.toLocaleString("pt-BR",{style:"currency",currency:moeda});
  const natures=Array.from(new Set(["Origem","Liderança","Técnica","Obra","Comercial","Capital","Propriedade",...map.participantes.flatMap(p=>[natureLabel(p.tipoCppCapital?.nome || "CPP Capital"),...(p.contribuicoes || []).filter(c=>c.indice>0).map(c=>natureLabel(c.tipoCpp?.nome || "Não classificado"))])]));
  const byNature=(p:typeof map.participantes[number],name:string)=>(natureLabel(p.tipoCppCapital?.nome || "CPP Capital")===name?(p.cppCapitalPercentual || 0):0)+(p.contribuicoes || []).filter(c=>natureLabel(c.tipoCpp?.nome || "Não classificado")===name).reduce((sum,c)=>sum+c.indice,0);
  const cell="px-3 py-3 align-top text-left";
  return <section className="min-w-0 space-y-4 rounded-lg border bg-card p-5"><h2 className="text-xl font-semibold">Mapa de Alocação Patrimonial Inicial</h2><p className="text-sm text-muted-foreground">Consulta e relatório. As participações abaixo são resultado da Base Econômica Inicial; não são campos de preenchimento.</p>
  <div className="overflow-x-auto"><table className="w-full text-sm"><caption className="sr-only">MAP Inicial por Sócio Aliado</caption><thead className="bg-muted"><tr>{["Sócio Aliado","Posição","CI","Aporte","CPP de Capital","Direito Econômico","CPP Total"].map(h=><th scope="col" key={h} className={cell}>{h}</th>)}</tr></thead><tbody>{map.participantes.map(p=><tr key={p.participantId || p.memberId} className="border-b"><th scope="row" className={cell}>{p.nome}</th><td className={cell}>{p.cargos?.join(" / ") || "—"}</td><td className={cell}>{formatBiaNumber(p.cotasInvestimento || 0,5)}</td><td className={cell}>{money(p.capitalComprometido || 0)}</td><td className={cell}>{formatBiaPercent(p.cppCapitalPercentual || 0)}<span className="block text-xs text-muted-foreground">{natureLabel(p.tipoCppCapital?.nome || "CPP Capital")}</span></td><td className={cell}>{p.contribuicoes?.some(c=>c.indice>0)?p.contribuicoes.filter(c=>c.indice>0).map(c=><p key={c.cargo}>{natureLabel(c.tipoCpp?.nome || "Não classificado")} {formatBiaPercent(c.indice)}<span className="block text-xs text-muted-foreground">{c.cargo}</span></p>):"—"}</td><td className={`${cell} font-semibold`}>{formatBiaPercent(p.mapPercentual || 0)}</td></tr>)}</tbody><tfoot className="bg-muted font-semibold"><tr><th scope="row" className={cell}>TOTAL</th><td/><td className={cell}>{formatBiaNumber(map.estrutura?.totalCotas || 0,5)}</td><td className={cell}>{money(map.valorOrigem)}</td><td className={cell}>{formatBiaPercent(100-map.divisorMultiplicador)}</td><td className={cell}>{formatBiaPercent(map.divisorMultiplicador)}</td><td className={cell}>{formatBiaPercent(map.participantes.reduce((sum,p)=>sum+(p.mapPercentual || 0),0))}</td></tr></tfoot></table></div>
  <details><summary className="cursor-pointer font-semibold">MAP detalhado — composição das CPPs por natureza</summary><div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted"><tr><th scope="col" className={cell}>Sócio</th>{natures.map(n=><th scope="col" key={n} className={cell}>CPP {n}</th>)}<th scope="col" className={cell}>CPP Total</th></tr></thead><tbody>{map.participantes.map(p=><tr key={p.participantId || p.memberId} className="border-b"><th scope="row" className={cell}>{p.nome}</th>{natures.map(n=><td key={n} className={cell}>{byNature(p,n)?formatBiaPercent(byNature(p,n)):"—"}</td>)}<td className={cell}>{formatBiaPercent(p.mapPercentual || 0)}</td></tr>)}</tbody><tfoot className="bg-muted font-semibold"><tr><th scope="row" className={cell}>TOTAL</th>{natures.map(n=><td key={n} className={cell}>{formatBiaPercent(map.participantes.reduce((sum,p)=>sum+byNature(p,n),0))}</td>)}<td className={cell}>{formatBiaPercent(map.participantes.reduce((sum,p)=>sum+(p.mapPercentual || 0),0))}</td></tr></tfoot></table></div></details>
  {map.estrutura && <details><summary className="cursor-pointer">Condições de capitalização e integralização</summary><div className="mt-3 space-y-2 text-sm"><p>Modalidade: {map.estrutura.modalidade.replaceAll("_"," ")}</p>{map.estrutura.instrumentos.map((i,n)=><p key={n}>{i.nome} · {money(i.valor)} · {formatBiaNumber(i.cotas,5)} CIs</p>)}<p>{map.estrutura.integralizacao.quantidade} parcelas · Primeiro vencimento: {map.estrutura.integralizacao.primeiroVencimento} · Intervalo de {map.estrutura.integralizacao.meses} meses</p><p>Correção contratual: {map.estrutura.integralizacao.correcao}. Sem reajuste automático.</p><p>{map.estrutura.integralizacao.observacoes}</p></div></details>}
  </section>;
}
type Composition = {valorOrigem:number; estrutura?:InitialEconomicStructure; participantes:InitialMapParticipantInput[]};

export function BiaEconomicStructureFields({value,onChange,members,moeda="BRL",readOnly=false,biaName}:{value:Composition;onChange:(v:Composition)=>void;members:Array<{id:string;nome?:string|null;Nome_de_usuario?:string|null}>;moeda?:string;readOnly?:boolean;biaName?:string}) {
  const s=value.estrutura || emptyEconomicStructure;
  const people=value.participantes;
  const types=useQuery<Array<{id:string;Nome:string}>>({queryKey:["/api/tipos-cpp"]});
  const cpp=(id:string)=>{const t=types.data?.find(t=>String(t.id)===id);return t?{id:String(t.id),nome:t.Nome}:undefined;};
  const money=(n:number)=>Number.isFinite(n)?new Intl.NumberFormat("pt-BR",{style:"currency",currency:moeda}).format(n):"Pendente";
  const structure=(patch:Partial<InitialEconomicStructure>)=>onChange({...value,estrutura:{...s,...patch}});
  const patch=(index:number,changes:Partial<InitialMapParticipantInput>)=>onChange({...value,participantes:people.map((p,i)=>i===index?{...p,...changes}:p)});
  const contribution=(i:number,j:number,changes:Partial<NonNullable<InitialMapParticipantInput["contribuicoes"]>[number]>)=>patch(i,{contribuicoes:people[i].contribuicoes!.map((c,n)=>n===j?{...c,...changes}:c)});
  const total=people.reduce((sum,p)=>sum+(Number.isFinite(p.cotasInvestimento)?p.cotasInvestimento!:0),0);
  const rights=people.flatMap(p=>p.contribuicoes || []);
  const dm=rights.every(c=>Number.isFinite(c.indice))?rights.reduce((sum,c)=>sum+c.indice,0):NaN;
  const unit=value.valorOrigem/s.totalCotas;
  const capitalComplete=people.length>0 && people.every(p=>Number.isFinite(p.cotasInvestimento));
  const contributed=capitalComplete?total*unit:NaN;
  const remaining=value.valorOrigem-contributed;
  const closed=capitalComplete && Number.isFinite(remaining) && Math.abs(remaining)<0.00001 && Math.abs(total-s.totalCotas)<0.00001;
  return <fieldset disabled={readOnly} className="min-w-0 space-y-6">
    <section className="space-y-2 rounded-lg border bg-card p-5"><h2 className="text-xl font-semibold">1. Identificação da BIA</h2><p>{biaName || "BIA em estruturação"}</p></section>
    <section className="space-y-4 rounded-lg border bg-card p-5"><h2 className="text-xl font-semibold">2. Valor de Origem</h2><div className="max-w-sm">
      <label>Valor de Origem ({moeda})<BiaNumberInput label="Valor de Origem" value={value.valorOrigem} onChange={valorOrigem=>onChange({...value,valorOrigem})}/></label>
    </div><p className="text-sm text-muted-foreground">Valor econômico que precisa ser integralizado para viabilizar a estrutura inicial da BIA. Deve fechar com os Aportes de Capital Iniciais.</p></section>
    <section className="space-y-4 rounded-lg border bg-card p-5"><h2 className="text-xl font-semibold">3. Forma de capitalização</h2><div className="grid gap-4 sm:grid-cols-2">
      <label>Forma de capitalização<select className={selectCss} value={s.modalidade} onChange={e=>structure({modalidade:e.target.value as InitialEconomicStructure["modalidade"]})}>{Object.entries(modalities).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
      {s.modalidade==="outra" && <label className="sm:col-span-2">Descreva a capitalização<Input value={s.descricao || ""} onChange={e=>structure({descricao:e.target.value})}/></label>}
    </div><p className="text-sm text-muted-foreground">Consórcio e financiamento não significam crédito aprovado ou liberado.</p>
    <details open={s.modalidade!=="recursos_proprios" || undefined}><summary className="cursor-pointer">Instrumentos de capitalização</summary><div className="mt-3 space-y-3">{s.instrumentos.map((row,i)=><div key={i} className="grid gap-3 rounded border p-3 sm:grid-cols-3"><label>Instrumento<Input aria-label={`Instrumento ${i+1}`} value={row.nome} onChange={e=>structure({instrumentos:s.instrumentos.map((r,n)=>n===i?{...r,nome:e.target.value}:r)})}/></label><label>Valor<BiaNumberInput label={`Valor do instrumento ${i+1}`} value={row.valor} onChange={valor=>structure({instrumentos:s.instrumentos.map((r,n)=>n===i?{...r,valor}:r)})}/></label><label>CIs<BiaNumberInput label={`CIs do instrumento ${i+1}`} value={row.cotas} decimals={5} onChange={cotas=>structure({instrumentos:s.instrumentos.map((r,n)=>n===i?{...r,cotas}:r)})}/></label><Button variant="ghost" onClick={()=>{if(window.confirm("Remover este instrumento?"))structure({instrumentos:s.instrumentos.filter((_,n)=>n!==i)});}}>Remover instrumento</Button></div>)}<div className="flex flex-wrap justify-between gap-3 rounded bg-muted p-3 font-semibold"><span>TOTAL</span><span>{s.instrumentos.length && s.instrumentos.every(r=>Number.isFinite(r.valor))?money(s.instrumentos.reduce((sum,r)=>sum+r.valor,0)):"Pendente"}</span><span>{s.instrumentos.length && s.instrumentos.every(r=>Number.isFinite(r.cotas))?formatBiaNumber(s.instrumentos.reduce((sum,r)=>sum+r.cotas,0),5):"Pendente"} CIs</span></div><Button variant="outline" onClick={()=>structure({instrumentos:[...s.instrumentos,{nome:"",valor:NaN,cotas:NaN}]})}>Adicionar instrumento</Button></div></details></section>
    <section className="space-y-4 rounded-lg border bg-card p-5"><h2 className="text-xl font-semibold">4. Cotas Iniciais — CI</h2><div className="grid items-end gap-4 sm:grid-cols-3"><div><p>Valor de Origem</p><strong>{money(value.valorOrigem)}</strong></div><label>Quantidade de Cotas Iniciais<BiaNumberInput label="Total de CIs" value={s.totalCotas} decimals={5} onChange={totalCotas=>structure({totalCotas})}/></label><div><p>Valor de cada Cota Inicial</p><strong>{money(unit)}</strong></div></div><p className="text-sm text-muted-foreground">CI é a unidade usada para fracionar e distribuir o Valor de Origem para aporte e integralização. CI não é CPP: organiza o aporte, não a participação patrimonial final.</p></section>
    <section data-testid="bei-capital-distribution" className="space-y-3 rounded-lg border bg-card p-4"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-semibold">5. Distribuição das Cotas Iniciais e Aportes de Capital</h2><Button variant="outline" onClick={()=>onChange({...value,participantes:[...people,{modeloCalculo:5,memberId:"",nome:"",tipo:"multiplicador",cargos:[],contribuicoes:[{cargo:"Contribuição individual",indice:NaN}],indiceContribuicao:NaN,pesoCapital:0,capitalComprometido:NaN,cotasInvestimento:NaN,naturezaCapital:"caixa"}]})}>+ Pessoa</Button></div>
    <p className="text-sm text-muted-foreground">Uma linha por pessoa. Cargos e natureza ficam nos detalhes.</p>
    <div aria-hidden="true" className="hidden grid-cols-[150px_minmax(0,2fr)_minmax(100px,1fr)_minmax(140px,1.3fr)] gap-3 rounded-t bg-muted px-2 py-2 text-xs font-semibold text-muted-foreground md:grid"><span>Tipo de Sócio</span><span>Sócio Aliado</span><span>Cotas Iniciais</span><span>Aporte de Capital</span></div>
    {people.map((p,i)=><div key={i} role="group" aria-label={`Participante ${i+1}`} className="space-y-1 border-b px-2 py-2 text-sm [&_input]:md:h-9 [&_select]:md:min-h-9"><div className="grid min-w-0 items-center gap-3 sm:grid-cols-2 md:grid-cols-[150px_minmax(0,2fr)_minmax(100px,1fr)_minmax(140px,1.3fr)]">
      <label className="min-w-0 md:order-2"><span className="md:sr-only">Sócio Aliado</span><select className={selectCss} value={p.memberId || ""} onChange={e=>{if(p.memberId && !window.confirm("Trocar a pessoa limpa as CIs e os direitos desta ficha. Continuar?"))return;const m=members.find(m=>String(m.id)===e.target.value);patch(i,{memberId:e.target.value,participantId:`member:${e.target.value}`,nome:m?.nome || m?.Nome_de_usuario || "",cotasInvestimento:NaN,capitalComprometido:NaN,tipoCppCapital:undefined,contribuicoes:p.contribuicoes?.map(c=>({...c,indice:NaN,tipoCpp:undefined}))});}}><option value="">Selecione</option>{members.map(m=><option key={m.id} value={m.id} disabled={people.some((p,n)=>n!==i && p.memberId===String(m.id))}>{m.nome || m.Nome_de_usuario || "Membro"}</option>)}</select></label>
      <label className="min-w-0 md:order-1"><span className="md:sr-only">Tipo de Sócio</span><select className={selectCss} value={p.tipo} onChange={e=>patch(i,{tipo:e.target.value as "guardiao"|"multiplicador"})}><option value="guardiao">Guardião</option><option value="multiplicador">Multiplicador</option></select></label>
      <label className="min-w-0 md:order-3"><span className="md:sr-only">Cotas Iniciais</span><BiaNumberInput label={`CIs — ${p.nome}`} value={p.cotasInvestimento ?? NaN} decimals={5} onChange={cotasInvestimento=>patch(i,{cotasInvestimento})}/></label><div className="min-w-0 md:order-4"><p className="md:sr-only">Aporte de Capital</p><strong>{money((p.cotasInvestimento ?? NaN)*unit)}</strong></div>
    </div><div className="flex flex-wrap items-start justify-between gap-x-3"><details className="min-w-0 py-1 [&[open]]:w-full"><summary className="cursor-pointer py-1 text-xs">Cargos ({p.contribuicoes?.length || 0}) e natureza{(p.cotasInvestimento || 0)>0 && !p.tipoCppCapital ? " · natureza pendente" : ""}</summary><div className="mt-3 space-y-3"><div className="grid gap-3 sm:grid-cols-2"><label>Forma do aporte<select className={selectCss} value={p.naturezaCapital || ""} onChange={e=>patch(i,{naturezaCapital:e.target.value as "caixa"|"nao_caixa"})}><option value="caixa">Dinheiro</option><option value="nao_caixa">Propriedade, bens ou direitos</option></select></label><label>Natureza do aporte<select className={selectCss} value={p.tipoCppCapital?.id || ""} onChange={e=>patch(i,{tipoCppCapital:cpp(e.target.value)})}><option value="">Selecione quando houver aporte</option>{types.data?.map(t=><option key={t.id} value={t.id}>{natureLabel(t.Nome)}</option>)}</select></label></div>
    {(p.contribuicoes || []).map((c,j)=><div key={j} className="flex flex-wrap items-end gap-2"><label className="min-w-0 flex-1">Cargo<select className={selectCss} value={c.cargo} onChange={e=>{if((c.indice>0 || c.tipoCpp) && !window.confirm("Trocar o cargo limpa o direito desta linha. Continuar?"))return;const rows=p.contribuicoes!.map((r,n)=>n===j?{cargo:e.target.value,indice:NaN}:r);patch(i,{contribuicoes:rows,cargos:rows.filter(c=>c.cargo!=="Contribuição individual").map(c=>c.cargo)});}}>{roles.map(role=><option key={role} disabled={role!==c.cargo && role!=="Contribuição individual" && people.some(p=>p.contribuicoes?.some(c=>c.cargo===role))}>{role}</option>)}</select></label>{p.contribuicoes!.length>1 && <Button variant="ghost" onClick={()=>{if(window.confirm("Remover este cargo e seu direito?")){const rows=p.contribuicoes!.filter((_,n)=>n!==j);patch(i,{contribuicoes:rows,cargos:rows.filter(c=>c.cargo!=="Contribuição individual").map(c=>c.cargo)});}}}>Remover cargo</Button>}</div>)}
    </div></details><div className="flex flex-wrap gap-1"><Button variant="ghost" className="px-2 text-xs md:h-8" onClick={e=>{const details=e.currentTarget.parentElement?.previousElementSibling;if(details instanceof HTMLDetailsElement)details.open=true;patch(i,{contribuicoes:[...(p.contribuicoes || []),{cargo:"Contribuição individual",indice:NaN}]});}}>Adicionar cargo</Button><Button variant="ghost" className="px-2 text-xs text-destructive md:h-8" onClick={()=>{if(window.confirm("Remover a pessoa, suas CIs e direitos?"))onChange({...value,participantes:people.filter((_,n)=>n!==i)});}}>Remover pessoa</Button></div></div></div>)}
    <div className="grid gap-3 rounded bg-muted p-3 text-sm sm:grid-cols-3"><div>Total de Cotas Iniciais<strong className="block">{capitalComplete?formatBiaNumber(total,5):"Pendente"}</strong></div><div>Aportes cadastrados<strong className="block">{money(contributed)} {closed?"✓":""}</strong></div><div>Saldo a integralizar<strong className="block">{money(remaining)} {closed?"✓":""}</strong></div></div><p className="text-xs text-muted-foreground">Saldo da composição do Valor de Origem, não comprovação de pagamento. Cotas distribuídas e aportes devem fechar os totais definidos.</p></section>
    <section className="space-y-4 rounded-lg border bg-card p-5"><h2 className="text-xl font-semibold">6. Forma de integralização</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
      <label>Forma<select className={selectCss} value={s.integralizacao.forma} onChange={e=>structure({integralizacao:{...s.integralizacao,forma:e.target.value as any,...(e.target.value==="a_vista"?{quantidade:1,meses:0}:{})}})}><option value="a_vista">À vista</option><option value="parcelado">Parcelado</option><option value="personalizado">Personalizado</option></select></label>
      <label>Quantidade de parcelas<BiaNumberInput label="Quantidade de parcelas" value={s.integralizacao.quantidade} decimals={0} onChange={quantidade=>structure({integralizacao:{...s.integralizacao,quantidade}})}/></label>
      <label>Primeiro vencimento<Input type="date" value={s.integralizacao.primeiroVencimento} onChange={e=>structure({integralizacao:{...s.integralizacao,primeiroVencimento:e.target.value}})}/></label>
      <label>Periodicidade<select className={selectCss} value={s.integralizacao.meses} onChange={e=>structure({integralizacao:{...s.integralizacao,meses:Number(e.target.value)}})}>{[[0,"Personalizada / única"],[1,"Mensal"],[2,"Bimestral"],[3,"Trimestral"],[6,"Semestral"],[12,"Anual"]].map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>
      <label>Correção contratual<Input value={s.integralizacao.correcao} onChange={e=>structure({integralizacao:{...s.integralizacao,correcao:e.target.value}})}/></label>
      <label>Detalhes do plano<Input value={s.integralizacao.observacoes || ""} onChange={e=>structure({integralizacao:{...s.integralizacao,observacoes:e.target.value}})}/></label>
    </div><p className="rounded bg-amber-50 p-3 text-sm text-amber-900">Planejamento contratual. IGP-M ou outro índice não será aplicado automaticamente. Parcelas nominais e beneficiários serão revisados e confirmados separadamente no Financeiro; esta etapa não gera lançamentos.</p></section>
    <section className="space-y-4 rounded-lg border bg-card p-5"><h2 className="text-xl font-semibold">7. Divisor Multiplicador</h2><p className="text-sm text-muted-foreground">Direitos Econômicos reconhecidos como contribuições à BIA, separados dos Aportes de Capital. Informe o índice por cargo; zero explícito indica ausência de direito.</p>
      <div className="hidden grid-cols-[1fr_2fr_1.5fr_1fr_1.5fr] gap-3 bg-muted p-3 text-sm font-medium lg:grid"><span>Tipo de Sócio</span><span>Beneficiário</span><span>Direito Econômico</span><span>Índice</span><span>Equivalência econômica</span></div>
      {people.map((p,i)=>(p.contribuicoes || []).map((c,j)=><div key={`${i}:${j}`} className="grid items-end gap-3 border-t py-3 lg:grid-cols-[1fr_2fr_1.5fr_1fr_1.5fr]"><div className="text-sm">{p.tipo==="guardiao"?"Guardião":"Multiplicador"}</div><div className="min-w-0 text-sm"><strong>{p.nome || "Selecione a pessoa"}</strong><p>{c.cargo}</p></div><label><span className="lg:sr-only">Direito Econômico</span><select aria-label={`Direito Econômico — ${p.nome} — ${c.cargo}`} className={selectCss} value={c.tipoCpp?.id || ""} onChange={e=>contribution(i,j,{tipoCpp:cpp(e.target.value)})}><option value="">Selecione quando positivo</option>{types.data?.map(t=><option key={t.id} value={t.id}>{natureLabel(t.Nome)}</option>)}</select></label><label><span className="lg:sr-only">Índice (%)</span><BiaNumberInput label={`Direito — ${p.nome} — ${c.cargo}`} value={c.indice} decimals={5} onChange={indice=>contribution(i,j,{indice})}/></label><div><p className="text-sm lg:sr-only">Equivalência econômica</p><strong>{money(value.valorOrigem*c.indice/100)}</strong></div></div>))}
      <div className="flex flex-wrap justify-between gap-3 rounded bg-muted p-4 font-semibold"><span>TOTAL</span><span>{Number.isFinite(dm)?formatBiaPercent(dm):"Pendente"}</span><span>{money(value.valorOrigem*dm/100)}</span></div><p className="text-sm text-muted-foreground">A equivalência econômica dos direitos não é somada ao Valor de Origem e não é Aporte de Capital. Fórmula: Valor de Origem × índice do direito.</p>
    </section>
    <section className="space-y-4 rounded-lg border bg-card p-5"><h2 className="text-xl font-semibold">8. Resumo da Base Econômica Inicial — BEI</h2><dl className="grid gap-x-6 gap-y-3 text-sm sm:grid-cols-2"><dt>Valor de Origem</dt><dd className="font-semibold">{money(value.valorOrigem)}</dd><dt>Forma de Capitalização</dt><dd>{modalities[s.modalidade]}</dd><dt>Cotas Iniciais</dt><dd>{Number.isFinite(s.totalCotas)?formatBiaNumber(s.totalCotas,5):"Pendente"} × {money(unit)}</dd><dt>Aportes de Capital</dt><dd>{money(contributed)} {closed?"✓":""}</dd><dt>Forma de Integralização</dt><dd>{s.integralizacao.forma==="a_vista"?"À vista":s.integralizacao.forma==="personalizado"?"Personalizada":`${Number.isFinite(s.integralizacao.quantidade)?s.integralizacao.quantidade:"—"} parcelas`} — {s.integralizacao.correcao || "Correção não informada"}</dd><dt>Direitos Econômicos Reconhecidos</dt><dd>{Number.isFinite(dm)?formatBiaPercent(dm):"Pendente"}</dd></dl><p className="rounded bg-blue-50 p-3 text-sm text-blue-900">A BEI é todo este arranjo econômico inicial, não um valor isolado. CI organiza o aporte. Direito Econômico reconhece a contribuição. CPP representa o patrimônio e aparece somente no MAP Inicial.</p></section>
    {types.isError && <p role="alert">Não foi possível carregar as classificações. <Button variant="outline" onClick={()=>types.refetch()}>Tentar novamente</Button></p>}
  </fieldset>;
}
